### ISSUE TITLE
Rtools conflicts with MinGW installers.  Reported by Mark Fowler.

### ISSUE THREAD

**Issue by johnoel** [admb-project/admb#105]

**Comment by arnima-github** [comment]
What MinGW installers? I think we should only release ADMB to work with Rtools. It's what Windows users have on their computer.

**Comment by johnoel** [comment]
The admb build files have been modified to add compiler information with the library filenames.  
The typical issue is a system that has both Rtools35 and MinGW-w64 installed.  If the installed ADMB libraries are not compatible with compiler that first appears first in PATH, then there will be a build linker error.  By adding compiler information the library filenames, the windows installer can now package multiple libraries. The admb script is able to determine which version library to link to.   

See merge

https://github.com/admb-project/admb/commit/fda93540bb59dd2617915a8567c1d6f96081bc99
