### ISSUE TITLE
admb is difficult to package correctly

### ISSUE THREAD

**Issue by alexandre-janniaux** [admb-project/admb#111]
Hi,

I tried to make an archlinux package for admb but there is a lot of different point that makes it uneasy to package correctly.
Basically I want it to be quite isolated from the rest of the system, but:

+ `include/contrib` is a very very common name, it should be in `include/admb/contrib/`
+  the `admb` scripts and the others should maybe use something standard like pkgconfig instead of rewriting it
+ it seems there is no real `make install` which can allow a prefix
+ there is a lot of unuseful files in dist/ directoy that poluate the install

I'm ready to fix these issues, but I would like an approval from your part before to be on the same track.

**Comment by johnoel** [comment]
Okay, I would like to see what you recommend.

**Comment by johnoel** [comment]
There is a 'make install' target to choose install directory.
admb-master/$ make INSTALL_DIR=/usr/local install

This install the admb distribution to /usr/local/admb and
adds a soft link to the admb script /usr/local/bin/admb -> /usr/local/admb/bin/admb.

This isolates the admb distribution from the system.  Let me know if this works for you.

**Comment by johnoel** [comment]
The dist directory has been simplified with the minimum files needed to build admb programs.
This should make it easier to package for any linux distribution.

# The default is now 'dist' instead of 'all'
**$ make**

**$ ls build/dist**

CHANGES.txt	README.txt	admb		include
LICENSE.txt	VERSION		bin		lib
