### ISSUE TITLE
Unable to use CTRL-C, 'n' and 'q' keyboard commands in Cygwin and Msys2 shells

### ISSUE THREAD

**Issue by johnoel** [admb-project/admb#112]

**Comment by iantaylor-NOAA** [comment]
This block of code seems to only be implemented for Microsoft Visual C, but I don't know the history of that:
https://github.com/admb-project/admb/blob/2044772105969a2ee6400c2fe961c2d754d64fa0/src/linad99/newfmin.cpp#L62-L86

**Comment by johnoel** [comment]
Yes, it should be defined for Windows.

**Comment by johnoel** [comment]
If you are using cygwin or msys2 shell, it uses mintty in the terminal which
does not correctly pass ctrl-c to the executable.

To workaround it, prefix winpty to run the program.

ie

$ winpty ./n2mvol.exe

Ctrl-C should now work.

The other alternative is to run the program using the stock Windows Command Prompt.

There is no solution for fixing this within admb, it is an issue with shell.

https://github.com/mintty/mintty/issues/684
