### ISSUE TITLE
Missing "total-clean" in tests/geolocation/GNUMakefile and tests/agemat/GNUMakefile

### ISSUE THREAD

**Issue by yukio-takeuchi** [admb-project/admb#122]
On Ubuntu 18.04 
``
make g++-all
``
command failed when
```
make --directory=geolocation total-clean
```
is called from command `` 	$(MAKE) --directory=src CC=gcc CXX=g++ copy`` which is third command of ``make g++-all`` with following error message 
```
make[4]: Entering directory '/home/yukiot/repository/admb/build/admb/tests/geolocation'
make[4]: *** No rule to make target 'total-clean'.  Stop.
```
In fact tests/geolocation/GNUMakefile lacks total-clean. tests/agemat/GNUMakefile also lacks total-clean.

They caused failure to build.
Probably this error should occur with  other C++  compilers  on Linux and Mac as well.

**Comment by johnoel** [comment]
Also needed bc2eb9a56997bcba3219200977e8013f6ab8479d

**Comment by johnoel** [comment]
The total-clean target in tests directory is used mainly to remove download git repositories such as glmmadmb and geolocation.  The *make --directory=tests total-clean* target should be run *BEFORE* if the top level * make all*  target is called.  If not, all downloaded files will be copied to the *build/admb* directory.

**Comment by johnoel** [comment]
Add e649a1cd5b217cd26f947b74c5f67b76a101fb63
