### ISSUE TITLE
init_vector_vector doesn't accept an integer (scalar) variable for phase

### ISSUE THREAD

**Issue by jimianelli** [admb-project/admb#13]
init_vector_vector doesn't accept an integer (scalar) variable for phase with typical error as:
```
mymod.cpp:52:15: error: no matching member function for call to 'allocate'
  MyRaggedMatrix.allocate(1,n,1,m,iPhase,"MyRaggedMatrix");
```

**Comment by johnoel** [comment]
Fixed in https://github.com/admb-project/admb/commit/8011a82cd7a9dfc53b688195fc0f85802678fe26
