### ISSUE TITLE
Porting to Raspberry PI

### ISSUE THREAD

**Issue by johnoel** [admb-project/admb#131]
https://groups.google.com/a/admb-project.org/d/msg/users/jWxnBLf9u7g/y74aucCJAwAJ

**Comment by alexandre-janniaux** [comment]
Is it planned to keep the Makefile build system?

**Comment by johnoel** [comment]
There is no plans to replace the current build system, but it is possible to add and use other build files with Make.

**Comment by johnoel** [comment]
Raspberry PI uses a arm64 processor which is the same as Apple M1.  So, it should be able to build, but I am unable to test it on the hardware.

**Comment by johnoel** [comment]
Tested okay for the macOS with arm64.
