### ISSUE TITLE
Broken links to mcmc docs

### ISSUE THREAD

**Issue by johnrsibert** [admb-project/admb#137]
Two of the three links at
http://www.admb-project.org/developers/mcmc/
do not seem to function.

**Comment by johnoel** [comment]
Seems to be accessible.  Can you try again?

**Comment by johnrsibert** [comment]
The links seem to work fine with chrome, but not with firefox the 
Presentation on MCMC options 
<http://www.admb-project.org/developers/mcmc/presentation-on-mcmc-options.pdf> 
and MCMC Guide for ADMB 
<http://www.admb-project.org/developers/mcmc/mcmc-guide-for-admb.pdf> 
links seem dead (even after clearing the cache and restarting firefox). 
The Updating the MCMC documentation 
<http://www.admb-project.org/developers/mcmc/updating-the-mcmc-documentation.html>  
seems fine.

Linux mint 19.3.

**Comment by iantaylor-NOAA** [comment]
All links work fine for me in Firefox on Windows 10.

John, can you open other PDFs in your Firefox on the admb-project.org site, like 
http://www.admb-project.org/docs/refcards/ADMBrefcard-USletter.pdf, or PDFs on other sites?
Could it just be a missing plugin: https://community.linuxmint.com/tutorial/view/352?

**Comment by johnrsibert** [comment]
Yes. That link downloads the reference card pdf using firefox, as it should

The problem may be that there is no link to 
http://www.admb-project.org/docs/ 
<http://www.admb-project.org/docs/refcards/ADMBrefcard-USletter.pdf>

I can paste http://www.admb-project.org/docs 
<http://www.admb-project.org/docs/refcards/ADMBrefcard-USletter.pdf>  
into the url window in firefox and I see links to a bunch of docs not 
accessible from the home page.

**Comment by johnoel** [comment]
Hi @johnrsibert, I can't seem to duplicate the error.  Are you still having issues accessing the pdfs with Firefox?
