### ISSUE TITLE
Provide more information on "debug" releases or on debugging in general?

### ISSUE THREAD

**Issue by iantaylor-NOAA** [admb-project/admb#150]
Thanks @johnoel for the ADMB 12.2 release and for providing a larger set of download options at https://github.com/admb-project/admb/releases.

For those of us less familiar with debugging tools, I think it would be helpful for users to provide more information about the debug versions of ADMB (what does the debug version get you other than a much larger executable?). It could be useful to include a sentence added to the release description, some text in the QuickStart documents, or links from those places to a more complete description elsewhere.

**Comment by johnoel** [comment]
Can you check if http://www.admb-project.org/downloads/admb-12.2/QuickStartMacOSZip.html is enough info?

**Comment by iantaylor-NOAA** [comment]
Looks good to me, thank you.
