### ISSUE TITLE
i5_array class lacks initialize() code body

### ISSUE THREAD

**Issue by wStockhausen** [admb-project/admb#155]
I'm getting a linker error that the i5_array::initialize() symbol does not exist. The i5_array class has a function initialize() defined in fvar.hpp but the body for the function does not seem to exist (it's not in i5arr.cpp, at least).

**Comment by johnoel** [comment]
Thank you @wStockhausen for reporting this issue.  The missing i5_array::initialize() function has been added (see [commit](https://github.com/admb-project/admb/commit/aafbc24267003c2f48f6734a783b9bb752abdeaa).

**Comment by johnoel** [comment]
Commit 4abdc61 is be for issue #156.
