### ISSUE TITLE
The admb executable called with a path should be stripped.

### ISSUE THREAD

**Issue by johnoel** [admb-project/admb#165]
Currently, if the executable is called with the path, the inputs will be read from the executable path and the outputs would be written to the executable path.

For example,

```
~/run$ ~/bin/model.exe
```

model.exe would try to read input files from ~/bin, then write outputs to ~/bin instead of ~/run directory.  The executable should read and write to the ~/run directory.

@jimianelli requested this feature.

**Comment by johnoel** [comment]
Hi @jimianelli and @Cole-Monnahan-NOAA, please test the [issue165](https://github.com/admb-project/admb/tree/issue165) branch.  It should be able to read and write to a directory that is different from where the executable is.

**Comment by Cole-Monnahan-NOAA** [comment]
I built this branch, compiled simple then tried this:

C:\Users\cole.monnahan\admb\examples\admb>simple\simple.exe
 Error trying to read in model data
 This is usual caused by a missing DAT file

Is that what you wanted me to test?

**Comment by johnoel** [comment]
Move simple.exe to another directory (ie C:\Users\cole.monnahan\bin\simple.exe).  

Then call simple.exe with it's full path,

```
C:\Users\cole.monnahan\admb\examples\admb\simple> C:\Users\cole.monnahan\bin\simple.exe
```

Check that program was able to read input files and write the outputs in the simple directory.

**Comment by Cole-Monnahan-NOAA** [comment]
Still fails. 

C:\Users\cole.monnahan\admb\examples\admb>C:\Users\cole.monnahan\test\simple\simple.exe
 Error trying to read in model data
 This is usual caused by a missing DAT file

C:\Users\cole.monnahan\admb\examples\admb>ls C:\Users\cole.monnahan\test\simple\
simple.dat  simple.exe  simple.tpl

**Comment by Cole-Monnahan-NOAA** [comment]
I misunderstood your original request. The idea is you have one master .exe file and multiple directories with e.g., different inputs and you want the inputs/outputs to always be in the directory. Yes this works:

C:\Users\cole.monnahan\admb\examples\admb\simple>C:\Users\cole.monnahan\test\simple\simple.exe

Initial statistics: 2 variables; iteration 0; function evaluation 0; phase 1
Function value   2.4980653e+01; maximum gradient component mag  -3.6127e+00
Var   Value    Gradient   |Var   Value    Gradient   |Var   Value    Gradient
  1  0.00000  -7.2781e-01 |  2  0.00000  -3.6127e+00 |

 - final statistics:
2 variables; iteration 7; function evaluation 19
Function value   3.4513e+00; maximum gradient component mag  -7.0014e-05
Exit code = 1;  converg criter   1.0000e-04
Var   Value    Gradient   |Var   Value    Gradient   |Var   Value    Gradient
  1  4.07818  -2.0898e-05 |  2  1.90909  -7.0014e-05 |
Estimating row 1 out of 2 for hessian
Estimating row 2 out of 2 for hessian
