### ISSUE TITLE
Broken links to model files in cubic spline example

### ISSUE THREAD

**Issue by iantaylor-NOAA** [admb-project/admb#183]
The previously undocumented option for splines discussed in #180 prompted me to revisit this example from 10 years ago http://www.admb-project.org/docs/tips/splines/ but some of the files linked there are broken.
@johnoel can those be resurrected somehow? The files I have on my computer seem to be from an earlier version that doesn't match the example results file that is available there.

**Comment by johnoel** [comment]
Okay @iantaylor-NOAA, try again...

**Comment by iantaylor-NOAA** [comment]
Links work. Thank you @johnoel!
