### ISSUE TITLE
Build and Run buttons missing in AD Studio

### ISSUE THREAD

**Issue by ammodytes2000** [admb-project/admb#214]
When I double-click the AD Studio shortcut, the emacs program opens but I don't see the build and run buttons.  I opened a .tpl, thinking maybe it required, but still nothing.  Has anyone run into this problem?

**Comment by ammodytes2000** [comment]
Wrong community, sorry

**Comment by johnoel** [comment]
Have you found a solution?

**Comment by arni-magnusson** [comment]
Hi, if you open an issue on https://github.com/admb-project/adstudio I'm sure we can identify and fix the problem.

**Comment by ammodytes2000** [comment]
Sorry for the late response; I was away for a couple of weeks.  No, I
haven't found a solution. I re-installed the AD studio but the same result
happened.  I'll try other things this week.
