### ISSUE TITLE
Compiling with C++20

### ISSUE THREAD

**Issue by archaic** [admb-project/admb#223]
Building with GCC, CMake and set(CMAKE_CXX_STANDARD 14|17) works fine, but when I change
it to CMAKE_CXX_STANDARD 20, I get the error below:

~/tool/admb-12.3/build/admb/include/tiny_ad.hpp:303:31: error: expected unqualified-id before ‘)’ token
  303 |     variable<1, nvar, Double>() { /* Do not zero-initialize */ }

**Comment by johnoel** [comment]
5d75b90 is fixes for the MacOS.

**Comment by johnoel** [comment]
@archaic, see changes in 9daea39 to fix the compiler (and runtime) issues in tiny_ad.hpp.

**Comment by johnoel** [comment]
Merged Pull #224.
