### ISSUE TITLE
Adding `dtweedie`

### ISSUE THREAD

**Issue by James-Thorson** [admb-project/admb#234]
There are several benefits to having a `dtweedie` function available that matches `R` and `TMB` syntax:

- Allows a random-effect smoother used at AFSC to explore the Tweedie to account for years with 0 catches.
- Allows SS3 to include a new data-weighting option that extends the Dirichlet-multinomial.

Could someone help me get the `dtweedie` function added to ADMB?

**Comment by johnoel** [comment]
Merged in Pull #241
