### ISSUE TITLE
Performance issue in 13.0-beta

### ISSUE THREAD

**Issue by arni-magnusson** [admb-project/admb#255]
Hi!

I've run some benchmarks that seem to indicate a performance issue in ADMB 13.0-beta:

https://github.com/admb-project/benchmarks

- Can other people confirm the relative runtime speeds they see when running ADMB 12.3 vs ADMB 13.0-beta on their model?
- Can we create an automated 12.3 vs 13.0-beta benchmark comparison for all the examples that come with ADMB, before we release 13.0?

The results seem to indicate a general performance issue, not specific to hardware, OS, or models. Unless I'm doing something wrong, of course :)

**Comment by arni-magnusson** [comment]
A quick check with a Stock Synthesis model would be an important use case.

**Comment by allanhicks** [comment]
Hi Arni,
Very interesting and important tests to do. I think that the SS team has
run some benchmarks automatically using GitHub Actions, and saw encouraging
results. You may want to view this interesting thread.

https://github.com/nmfs-stock-synthesis/stock-synthesis/issues/257#issuecomment-1124950348

I haven’t run any tests, but Kathryn, Cole, Ian, Rick, Johnoel, and others
would have more insight.

Good luck,
Allan

**Comment by johnoel** [comment]
Thanks Arni, for catching that.  Please check again, it should be better.

**Comment by johnoel** [comment]
Used more low level c coding in #258.

**Comment by arni-magnusson** [comment]
Thanks for addressing the problem, Johnoel.

Unfortunately, the performance issue seems to be persist in Windows.

See the newest benchmark [plot](https://github.com/admb-project/benchmarks/blob/main/2022_07_10/plot.pdf).

**Comment by Rick-Methot-NOAA** [comment]
Arni,
Your results are opposite of the performance Kathryn reported last week in which ADMB 13.0 was ~30% shorter runtimes than 12.3. Not sure if that was linux or windows.

**Comment by iantaylor-NOAA** [comment]
One more thing to add on ADMB 13.0 performance. 
@k-doering-NOAA just did some tests with Stock Synthesis compiled with the fast option ("admb -f") and found that whereas with ADMB 12.3, the average model run with the fast executable took only 69% of the time as one compiled with the safe one, adding "-f" to when compiling in pre-release ADMB 13.0 slowed it down, with average run time at 133% of the safe version. More detail is at https://github.com/nmfs-stock-synthesis/workflows/issues/42 or from @k-doering-NOAA.

Some of this may be specific to Stock Synthesis, so it might be useful if @arni-magnusson can add a test of the fast option to his benchmarks.

Personally, I would much prefer performance improvements to the safe executable (as we've now seen on linux as discussed earlier in this issue). If the fast option isn't showing much benefit, I don't think it would be a big loss to leave it out of ADMB 13.0, but that's just me.

**Comment by k-doering-NOAA** [comment]
Thanks @iantaylor-NOAA , just adding for clarity that this was on linux.

**Comment by johnoel** [comment]
Hi @arni-magnusson, can you give it another check on your computers.  I get pretty close results.
