### ISSUE TITLE
ADMB 13 model name in console output is always as it was compiled

### ISSUE THREAD

**Issue by k-doering-NOAA** [admb-project/admb#259]
For the admb 13 branch, I noticed that even if I rename the .exe file produced after compiling a model, the console output still reports the name it was compiled under.

For example, if I compile a model ss.tpl with admb 13 to get ss.exe, then rename ss.exe to ss_admb_13.exe and run the model, then the last line of the console output is still:

```
Finished running model 'ss' after 2 m 50 s.
```

What I would prefer to see is:
```
Finished running model 'ss_admb_13' after 2 m 50 s.
```

Just wondering if there is a way to get this output.

**Comment by johnoel** [comment]
I just tested this and it prints the right changed executable name.  Can you recheck?

**Comment by k-doering-NOAA** [comment]
I just tested again using the compiled version of admb from https://github.com/admb-project/admb/actions/runs/2420289483 and still see the same original issue.

**Comment by johnoel** [comment]
Hi @k-doering-NOAA , can you check again with admb-13.0 branch?

**Comment by Cole-Monnahan-NOAA** [comment]
This is a function I helped write. It's called in a few places, namely the parts of code I modified. Source is:
https://github.com/admb-project/admb/blob/admb-13.0/src/nh99/hmc_functions.cpp#L63

I wrote it for HMC stuff but then used it for the console changes for optimization too. Maybe easiest to fix the function?

**Comment by johnoel** [comment]
Hi @k-doering-NOAA, can you recheck it?

**Comment by k-doering-NOAA** [comment]
Thanks @johnoel, I can take a look later today
