### ISSUE TITLE
problems using install from admb-13.0-linux.zip

### ISSUE THREAD

**Issue by iantaylor-NOAA** [admb-project/admb#272]
I'm revising some GitHub Actions to compile Stock Synthesis with ADMB 13.0 instead of 12.3 and ran into some problems with the Linux setup.

Using the "ubuntu-20.04" runner image (listed in https://github.com/actions/runner-images#available-environments), I got these errors
```
tpl2cpp: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by tpl2cpp)
tpl2rem: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by tpl2rem)
```
I got that same message on a local Linux server running "gcc version 4.8.5 20150623 (Red Hat 4.8.5-44)".

Switching the GitHub Action to the newer "ubuntu-22.04" runner produced this error:
```
Error: Error: Unable to find libadmb-contrib-x86_64-linux-g++11.a
```
see context of the error at https://github.com/nmfs-stock-synthesis/stock-synthesis/runs/8126396737?check_suite_focus=true#step:21:22.

The workflow I've modified (from something that @k-doering-NOAA had working well for ADMB 12.3) is here: https://github.com/nmfs-stock-synthesis/workflows/blob/admb13/.github/workflows/build-ss3.yml.
It now works for both Windows and Mac with ADMB 13.0. I could set up the Linux compile to build from source, which is what the Mac is doing, but that takes about 40 minutes vs 6 minutes for Windows (using admb-13.0-windows.zip).

@johnoel, any advice on what might be going wrong?

Also, FYI, when unzipping the admb-13.0-src.zip release on Windows without admin privileges I get the following messages:
```
Cannot create symbolic link : A required privilege is not held by the client. : C:\Users\ian.taylor\Downloads\admb-13.0-src\admb-13.0\src\df1b2-separable\remod10
Cannot create symbolic link : A required privilege is not held by the client. : C:\Users\ian.taylor\Downloads\admb-13.0-src\admb-13.0\tests\pella_t\pella_t.dat
```

**Comment by johnoel** [comment]
Bummer, I will correct the build files to avoid incompatible shared library linking.  Also, I will build support for gcc-11.

**Comment by iantaylor-NOAA** [comment]
Thanks @johnoel, thanks for working on this.
I'm find working around the issue by building from source on linux for now.

**Comment by johnoel** [comment]
Okay @iantaylor-NOAA, update the linux zip file.  Please give it a try...

**Comment by iantaylor-NOAA** [comment]
Works great in the GitHub actions. Thank you @johnoel!

On my local linux server I still get some errors about missing stuff (pasted below just in case it helps someone else searching for an error), but I don't expect to ever be compiling there now that the github action is working. And if I do need to do so, I just use ADMB 13.0 built from source which worked fine.
```
*** Linking: ss.obj
g++ --static -std=c++11 -O3 -oss ss.obj "/home/itaylor/h_itaylor/admb/admb-13.0/lib/libadmb-contrib-x86_64-linux-g++4.a"

/usr/bin/ld: cannot find -lstdc++
/usr/bin/ld: cannot find -lm
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
Error: Could not build ss
```
