### ISSUE TITLE
missing ADMB 13.1 assets?

### ISSUE THREAD

**Issue by iantaylor-NOAA** [admb-project/admb#281]
Hi @johnoel,
Thank you for the 13.1 release!
It looks like some of the assets associated with the 13.0 release are not available for 13.1. For instance, I see you updated this file https://github.com/admb-project/admb/blob/main/docs/install/QuickStartWindows.md, but the link to admb-13.1-windows.exe doesn't work because that asset doesn't seem to exist. Do you think you can add the assets or should folks expect to just build from source?

**Comment by johnoel** [comment]
The rest of installers will be uploaded by December 23, 2022.  The installers are currently building on GitHub Actions.

**Comment by iantaylor-NOAA** [comment]
Of course, that makes sense, thank you @johnoel.

**Comment by iantaylor-NOAA** [comment]
Following up to say that the newly posted admb-13.1-windows.exe installer and the installed ADMB 13.1 itself worked just fine on my NOAA computer.

**Comment by johnoel** [comment]
Thanks Ian for testing
