### ISSUE TITLE
Objective function output precision

### ISSUE THREAD

**Issue by johnrsibert** [admb-project/admb#29]
The precision of reported objective function value in the .par output file should be increased. See nh99/model.cpp for source code, void initial_params::save()

Does any one depend on the number digits reported in the .par file to generate customized reports?

**Comment by cgrandin** [comment]
Could add a switch for number of decimal places, with the default remaining what it is. Then it wouldn't disrupt anyone's projects

**Comment by johnrsibert** [comment]
A command line switch, as Chris suggests, could work. Alternatively, some sort of set_output_precision(...) function could be called in TOP_OF_MAIN_SECTION. Either solution would probably require a lot of code changes I suspect. 

**Perhaps I'm the only user who wants to see more precision.** I solved my problem in my working copy by changing  line 417 in src/nh99/model.cpp from
      `parfile << setshowpoint()`
to
     ` parfile << setshowpoint() << setprecision(15)
`

**Comment by johnoel** [comment]
Merged change
