### ISSUE TITLE
Problem with building in home directory

### ISSUE THREAD

**Issue by kellijohnson** [admb-project/admb#33]
I had an issue with building in the home directory "c:\~\admb" on a windows 64x machine using mingw and msys. The issue was fixed by moving to "c:\admb". See below for emails between @johnoel and @kellijohnson

On 3/31/2016 11:21 AM, Johnoel Ancheta wrote:
        Move or clone the admb directory to
        c:\admb
        Then
        $ cd /c/admb
        Try and rebuild
        $ make clean
        $ make

On Thu, Mar 31, 2016 at 5:42 AM, Kelli Johnson wrote:
            I am trying to build admb from source on a windows machine, where I
            have cloned the github repo and I have mingw and msys. When I type
            make I get the following error:
            make[3]: Entering directory '/c/~admb/src'
            make --directories=src CC=gcc CXX=g++ SHARED=-shared shared
            mkdir -p ../build/objects/dist/
            g++ -shared  -o ../build/dist/lib/libadmb.so -Wl,--whole-archive
            ../build/dist/l
            ib/libadmb-shared.a -Wl,--no-whole-archive
            ../build/dist/lib/libadmb-shared.a: member
            ../build/dist/lib/libadmb-shared.a(sh
            ared-saflp-linad99-adglobl.obj) in archive is not an object
            collect2.exe: error: ld returned 1 exit status
            make[3]: *** [shared] Error 1

**Comment by johnoel** [comment]
Most likely a bad revision that had a broken build.  Current revision can 
be built in home directory.
