### ISSUE TITLE
Nuts in ADMB

### ISSUE THREAD

**Issue by johnoel** [admb-project/admb#35]
Work with Cole Monnahan to add in.

**Comment by johnoel** [comment]
See 
https://github.com/kaskr/adcomp/blob/master/TMB/R/mcmc.R

Start from 
http://www.admb-project.org/documentation/api/hybmcmc_8cpp_source.html#l00086

**Comment by colemonnahan** [comment]
This functionality is now merged into the main master branch. See the accompanying R package at www.github.com/colemonnahan/adnuts
