### ISSUE TITLE
Change main site from Plone to Wordpress

### ISSUE THREAD

**Issue by johnoel** [admb-project/admb#53]
The change will be on August 15, 2016.

http://admb-project-org.admb-foundation.org

**Comment by tcwain** [comment]
The new site looks good and works well! Just a comment on content: The new homepage says the site is for both ADMB and TMB, but the Documentation, Download, and Help tabs only cover ADMB. Is there a plan to add TMB info/links?

**Comment by cgrandin** [comment]
It looks great, and is pretty much bug-free. I only found issues with the following:
In the FAQ page (http://admb-project-org.admb-foundation.org/documentation/faq), there are some wrong/messed up links under "Who is currently developing ADMB?":

admb-project.org/developers/core-team
https://github.com/admb-project/admb/blob/master/src/nh99/model7.cpp

**Comment by johnrsibert** [comment]
Good point, Tom. The revisions to the ADMB home page were implemented on 
short notice during the last developer workshop. All of the TMB 
documentation and download information are to be found on the TMB github 
sites, linked to the new home page. Both of these projects depend on 
volunteers. So if someone is interested and has the skills to integrate 
TMB links into the new site, please volunteer.
Thanks,
John

John Sibert
Emeritus Researcher, SOEST
University of Hawaii at Manoa
Honolulu HI (GMT-10)
808-294-3842

Visit the ADMB project http://admb-project.org/

**Comment by johnoel** [comment]
Thanks Chris, corrected links.

**Comment by tcwain** [comment]
Once I'm a bit more familiar with TMB (my next big project), I might be
able to help with the web links.

Tom

**Comment by taylori** [comment]
Hi Johnoel,
The new website looks good in general.

The FAQ could probably benefit from a larger scale update and I haven't had
time to contribute to it (or other parts of ADMB) in a while. I'm happy to
have my email replaced as as contact person associated with the FAQ if
somebody else wants to step up. Then again, I never get emails for
suggested changes anyway.
-Ian

**Comment by johnoel** [comment]
Hi Ian,

Would you mind, if we kept you as the maintainer?  If so, I will set you up
with an account.

johnoel

**Comment by taylori** [comment]
I can continue. If folks have suggestions for changes to the FAQ, please
send them to me.

**Comment by johnoel** [comment]
Completed move to easier to use GitHub pages instead of Wordpress.
