### ISSUE TITLE
tiny_ad_re fails for intel c++ 2018 beta

### ISSUE THREAD

**Issue by johnoel** [admb-project/admb#79]

**Comment by kaskr** [comment]
I've seen similar issues when using icpc (14.0.2) even for trivial standalone `tiny_ad` examples. It seems to be caused by over optimization:

* `-O3` gives wrong results unless `-fp-model precise` is also set.
* `-O2` gives correct results.

**Comment by johnoel** [comment]
tiny_ad_re runs fine with Intel C++ version 19
