### ISSUE TITLE
Possible typo in sqr(const dvector&)

### ISSUE THREAD

**Issue by johnoel** [admb-project/admb#81]
tmp.elem(i)=sqrt(v1.elem(i));

sqrt should be sqr or v1.elem(i) * v1.elem(i)?

**Comment by johnrsibert** [comment]
I looks like this code was duplicated from the preceding dvector sqrt(const dvector& v1)  function and never correctly completed.

It should be
tmp.elem(i)=sqr(v1.elem(i));
or
tmp.elem(i)=v1.elem(i) * v1.elem(i) ; 

Also, some dox would be helpful.
