### ISSUE TITLE
sort out "ADMB only supports 250 initial parameter objects"

### ISSUE THREAD

**Issue by taylori** [admb-project/admb#89]
In [this thread](https://groups.google.com/a/admb-project.org/forum/#!topic/users/D2f2GVVIx8g), Dave Fournier suggested that a change to line 27 of [/src/nh99/model.cpp](https://github.com/admb-project/admb/blob/master/src/nh99/model.cpp#L27) from
`const int initial_params::max_num_initial_params=250;`
to
`const int initial_params::max_num_initial_params=4000;`
would loosen a limitation on the code and allow some larger models to work that are currently getting the error "ADMB only supports 250 initial parameter objects".

There is some kind of switch related to BIG_INIT_PARAMS, but it's not clear how that works or whether there would ever be a need for the smaller limit given current computing setups.

**Comment by johnoel** [comment]
Used recommendation.
